[book]
authors = ["cui"]
language = "zh-CN"
src = "src"
title = "游戏开发系统化知识地图"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
